/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  siteUrl?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  newsletterEnabled?: boolean;
  newsletterApiKey?: string;
  newsletterFormId?: string;
  socialLinks?: {
    twitter?: string;
    github?: string;
    linkedin?: string;
    instagram?: string;
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
  _type: "image";
  _key: string;
} | {
  _key: string;
} & Code>;

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  language?: "hi" | "en";
  tags?: Array<string>;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt?: string;
  seoDescription?: string;
};

export type Poem = {
  _id: string;
  _type: "poem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  form?: "ghazal" | "freeVerse" | "storyPoem";
  language?: "hi" | "ur" | "en";
  tags?: Array<string>;
  audioFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    description?: string;
    _type: "file";
  };
  body?: string;
  transliteration?: string;
  translation?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt?: string;
  seoDescription?: string;
};

export type Essay = {
  _id: string;
  _type: "essay";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  tags?: Array<string>;
  excerpt?: string;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt?: string;
  seoDescription?: string;
};

export type Journal = {
  _id: string;
  _type: "journal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  cadence?: "daily" | "weekly" | "monthly";
  tags?: Array<string>;
  excerpt?: string;
  body?: BlockContent;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt?: string;
  seoDescription?: string;
  dayNumber?: number;
  stats?: {
    marketing?: number;
    building?: number;
    conversationsTotal?: number;
    conversationsQualified?: number;
    conversationsGhost?: number;
    conversationsWrongFit?: number;
    goalProgress?: number;
    runwayCurrent?: number;
    runwayTotal?: number;
  };
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = SiteSettings | BlockContent | Story | Poem | Essay | Journal | Author | Code | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/sanity.queries.ts
// Variable: journalsQuery
// Query: *[_type == "journal" && defined(publishedAt)] | order(date desc) {    _id,    title,    slug,    date,    cadence,    tags,    excerpt,    publishedAt,    "author": author->name  }
export type JournalsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  cadence: "daily" | "monthly" | "weekly" | null;
  tags: Array<string> | null;
  excerpt: string | null;
  publishedAt: string | null;
  author: string | null;
}>;
// Variable: journalBySlugQuery
// Query: *[_type == "journal" && slug.current == $slug][0] {    _id,    title,    slug,    date,    cadence,    tags,    excerpt,    body,    publishedAt,    seoDescription,    "author": author->{      name,      image,      bio    }  }
export type JournalBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  cadence: "daily" | "monthly" | "weekly" | null;
  tags: Array<string> | null;
  excerpt: string | null;
  body: BlockContent | null;
  publishedAt: string | null;
  seoDescription: string | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;
// Variable: essaysQuery
// Query: *[_type == "essay" && defined(publishedAt)] | order(date desc) {    _id,    title,    slug,    date,    tags,    excerpt,    coverImage,    publishedAt,    "author": author->name  }
export type EssaysQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  tags: Array<string> | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  author: string | null;
}>;
// Variable: essayBySlugQuery
// Query: *[_type == "essay" && slug.current == $slug][0] {    _id,    title,    slug,    date,    tags,    excerpt,    coverImage,    body,    publishedAt,    seoDescription,    "author": author->{      name,      image,      bio    }  }
export type EssayBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  tags: Array<string> | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  publishedAt: string | null;
  seoDescription: string | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;
// Variable: poemsQuery
// Query: *[_type == "poem" && defined(publishedAt)] | order(date desc) {    _id,    title,    slug,    date,    form,    language,    tags,    "audioFile": audioFile.asset->url,    publishedAt,    "author": author->name  }
export type PoemsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  form: "freeVerse" | "ghazal" | "storyPoem" | null;
  language: "en" | "hi" | "ur" | null;
  tags: Array<string> | null;
  audioFile: string | null;
  publishedAt: string | null;
  author: string | null;
}>;
// Variable: poemBySlugQuery
// Query: *[_type == "poem" && slug.current == $slug][0] {    _id,    title,    slug,    date,    form,    language,    tags,    "audioFile": audioFile.asset->url,    body,    transliteration,    translation,    publishedAt,    seoDescription,    "author": author->{      name,      image,      bio    }  }
export type PoemBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  form: "freeVerse" | "ghazal" | "storyPoem" | null;
  language: "en" | "hi" | "ur" | null;
  tags: Array<string> | null;
  audioFile: string | null;
  body: string | null;
  transliteration: string | null;
  translation: string | null;
  publishedAt: string | null;
  seoDescription: string | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;
// Variable: storiesQuery
// Query: *[_type == "story" && defined(publishedAt)] | order(date desc) {    _id,    title,    slug,    date,    language,    tags,    excerpt,    coverImage,    publishedAt,    "author": author->name  }
export type StoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  language: "en" | "hi" | null;
  tags: Array<string> | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  author: string | null;
}>;
// Variable: storyBySlugQuery
// Query: *[_type == "story" && slug.current == $slug][0] {    _id,    title,    slug,    date,    language,    tags,    excerpt,    coverImage,    body,    publishedAt,    seoDescription,    "author": author->{      name,      image,      bio    }  }
export type StoryBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  date: string | null;
  language: "en" | "hi" | null;
  tags: Array<string> | null;
  excerpt: string | null;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  publishedAt: string | null;
  seoDescription: string | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;
// Variable: podcastsQuery
// Query: *[_type == "podcast" && defined(publishedAt)] | order(date desc) {    _id,    title,    slug,    date,    tags,    excerpt,    videoUrl,    coverImage,    duration,    publishedAt,    "author": author->name  }
export type PodcastsQueryResult = Array<never>;
// Variable: podcastBySlugQuery
// Query: *[_type == "podcast" && slug.current == $slug][0] {    _id,    title,    slug,    date,    tags,    excerpt,    videoUrl,    coverImage,    duration,    publishedAt,    seoDescription,    "author": author->{      name,      image,      bio    }  }
export type PodcastBySlugQueryResult = null;
// Variable: latestContentQuery
// Query: {  "journals": *[_type == "journal" && defined(publishedAt)] | order(date desc)[0...4] {    _id,    _type,    title,    slug,    date,    excerpt,    "author": author->name  },  "essays": *[_type == "essay" && defined(publishedAt)] | order(date desc)[0...4] {    _id,    _type,    title,    slug,    date,    excerpt,    coverImage,    "author": author->name  },  "podcasts": *[_type == "podcast" && defined(publishedAt)] | order(date desc)[0...4] {    _id,    _type,    title,    slug,    date,    excerpt,    videoUrl,    coverImage,    duration,    "author": author->name  },  "poems": *[_type == "poem" && defined(publishedAt)] | order(date desc)[0...3] {    _id,    _type,    title,    slug,    date,    language,    "author": author->name  },  "stories": *[_type == "story" && defined(publishedAt)] | order(date desc)[0...3] {    _id,    _type,    title,    slug,    date,    excerpt,    coverImage,    "author": author->name  }}
export type LatestContentQueryResult = {
  journals: Array<{
    _id: string;
    _type: "journal";
    title: string | null;
    slug: Slug | null;
    date: string | null;
    excerpt: string | null;
    author: string | null;
  }>;
  essays: Array<{
    _id: string;
    _type: "essay";
    title: string | null;
    slug: Slug | null;
    date: string | null;
    excerpt: string | null;
    coverImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    } | null;
    author: string | null;
  }>;
  podcasts: Array<never>;
  poems: Array<{
    _id: string;
    _type: "poem";
    title: string | null;
    slug: Slug | null;
    date: string | null;
    language: "en" | "hi" | "ur" | null;
    author: string | null;
  }>;
  stories: Array<{
    _id: string;
    _type: "story";
    title: string | null;
    slug: Slug | null;
    date: string | null;
    excerpt: string | null;
    coverImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      caption?: string;
      alt?: string;
      _type: "image";
    } | null;
    author: string | null;
  }>;
};
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    title,    description,    siteUrl,    ogImage,    newsletterEnabled,    socialLinks  }
export type SiteSettingsQueryResult = {
  title: string | null;
  description: string | null;
  siteUrl: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  newsletterEnabled: boolean | null;
  socialLinks: {
    twitter?: string;
    github?: string;
    linkedin?: string;
    instagram?: string;
  } | null;
} | null;
// Variable: allTagsQuery
// Query: {  "journalTags": array::unique(*[_type == "journal" && defined(tags)].tags[]),  "essayTags": array::unique(*[_type == "essay" && defined(tags)].tags[]),  "poemTags": array::unique(*[_type == "poem" && defined(tags)].tags[]),  "storyTags": array::unique(*[_type == "story" && defined(tags)].tags[])}
export type AllTagsQueryResult = {
  journalTags: Array<string | null>;
  essayTags: Array<string | null>;
  poemTags: Array<string | null>;
  storyTags: Array<string | null>;
};
// Variable: contentByTagQuery
// Query: *[defined(tags) && $tag in tags && defined(publishedAt)] | order(date desc) {    _id,    _type,    title,    slug,    date,    tags,    excerpt,    "author": author->name  }
export type ContentByTagQueryResult = Array<{
  _id: string;
  _type: "essay";
  title: string | null;
  slug: Slug | null;
  date: string | null;
  tags: Array<string> | null;
  excerpt: string | null;
  author: string | null;
} | {
  _id: string;
  _type: "journal";
  title: string | null;
  slug: Slug | null;
  date: string | null;
  tags: Array<string> | null;
  excerpt: string | null;
  author: string | null;
} | {
  _id: string;
  _type: "poem";
  title: string | null;
  slug: Slug | null;
  date: string | null;
  tags: Array<string> | null;
  excerpt: null;
  author: string | null;
} | {
  _id: string;
  _type: "story";
  title: string | null;
  slug: Slug | null;
  date: string | null;
  tags: Array<string> | null;
  excerpt: string | null;
  author: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"journal\" && defined(publishedAt)] | order(date desc) {\n    _id,\n    title,\n    slug,\n    date,\n    cadence,\n    tags,\n    excerpt,\n    publishedAt,\n    \"author\": author->name\n  }\n": JournalsQueryResult;
    "\n  *[_type == \"journal\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    date,\n    cadence,\n    tags,\n    excerpt,\n    body,\n    publishedAt,\n    seoDescription,\n    \"author\": author->{\n      name,\n      image,\n      bio\n    }\n  }\n": JournalBySlugQueryResult;
    "\n  *[_type == \"essay\" && defined(publishedAt)] | order(date desc) {\n    _id,\n    title,\n    slug,\n    date,\n    tags,\n    excerpt,\n    coverImage,\n    publishedAt,\n    \"author\": author->name\n  }\n": EssaysQueryResult;
    "\n  *[_type == \"essay\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    date,\n    tags,\n    excerpt,\n    coverImage,\n    body,\n    publishedAt,\n    seoDescription,\n    \"author\": author->{\n      name,\n      image,\n      bio\n    }\n  }\n": EssayBySlugQueryResult;
    "\n  *[_type == \"poem\" && defined(publishedAt)] | order(date desc) {\n    _id,\n    title,\n    slug,\n    date,\n    form,\n    language,\n    tags,\n    \"audioFile\": audioFile.asset->url,\n    publishedAt,\n    \"author\": author->name\n  }\n": PoemsQueryResult;
    "\n  *[_type == \"poem\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    date,\n    form,\n    language,\n    tags,\n    \"audioFile\": audioFile.asset->url,\n    body,\n    transliteration,\n    translation,\n    publishedAt,\n    seoDescription,\n    \"author\": author->{\n      name,\n      image,\n      bio\n    }\n  }\n": PoemBySlugQueryResult;
    "\n  *[_type == \"story\" && defined(publishedAt)] | order(date desc) {\n    _id,\n    title,\n    slug,\n    date,\n    language,\n    tags,\n    excerpt,\n    coverImage,\n    publishedAt,\n    \"author\": author->name\n  }\n": StoriesQueryResult;
    "\n  *[_type == \"story\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    date,\n    language,\n    tags,\n    excerpt,\n    coverImage,\n    body,\n    publishedAt,\n    seoDescription,\n    \"author\": author->{\n      name,\n      image,\n      bio\n    }\n  }\n": StoryBySlugQueryResult;
    "\n  *[_type == \"podcast\" && defined(publishedAt)] | order(date desc) {\n    _id,\n    title,\n    slug,\n    date,\n    tags,\n    excerpt,\n    videoUrl,\n    coverImage,\n    duration,\n    publishedAt,\n    \"author\": author->name\n  }\n": PodcastsQueryResult;
    "\n  *[_type == \"podcast\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    date,\n    tags,\n    excerpt,\n    videoUrl,\n    coverImage,\n    duration,\n    publishedAt,\n    seoDescription,\n    \"author\": author->{\n      name,\n      image,\n      bio\n    }\n  }\n": PodcastBySlugQueryResult;
    "\n{\n  \"journals\": *[_type == \"journal\" && defined(publishedAt)] | order(date desc)[0...4] {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    excerpt,\n    \"author\": author->name\n  },\n  \"essays\": *[_type == \"essay\" && defined(publishedAt)] | order(date desc)[0...4] {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    excerpt,\n    coverImage,\n    \"author\": author->name\n  },\n  \"podcasts\": *[_type == \"podcast\" && defined(publishedAt)] | order(date desc)[0...4] {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    excerpt,\n    videoUrl,\n    coverImage,\n    duration,\n    \"author\": author->name\n  },\n  \"poems\": *[_type == \"poem\" && defined(publishedAt)] | order(date desc)[0...3] {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    language,\n    \"author\": author->name\n  },\n  \"stories\": *[_type == \"story\" && defined(publishedAt)] | order(date desc)[0...3] {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    excerpt,\n    coverImage,\n    \"author\": author->name\n  }\n}\n": LatestContentQueryResult;
    "\n  *[_type == \"siteSettings\"][0] {\n    title,\n    description,\n    siteUrl,\n    ogImage,\n    newsletterEnabled,\n    socialLinks\n  }\n": SiteSettingsQueryResult;
    "\n{\n  \"journalTags\": array::unique(*[_type == \"journal\" && defined(tags)].tags[]),\n  \"essayTags\": array::unique(*[_type == \"essay\" && defined(tags)].tags[]),\n  \"poemTags\": array::unique(*[_type == \"poem\" && defined(tags)].tags[]),\n  \"storyTags\": array::unique(*[_type == \"story\" && defined(tags)].tags[])\n}\n": AllTagsQueryResult;
    "\n  *[defined(tags) && $tag in tags && defined(publishedAt)] | order(date desc) {\n    _id,\n    _type,\n    title,\n    slug,\n    date,\n    tags,\n    excerpt,\n    \"author\": author->name\n  }\n": ContentByTagQueryResult;
  }
}
